version: 3

tasks:
  clean:
    - rm -rf ./.cache || true
    - rm -rf ./.task || true
    - rm -rf ./dist || true

  lint:
    vars:
      MODE:
        ref: .SWAPI_OUTPUT_MODE | default .MODE | default "development"
      TSCONFIG: './tsconfig/tsconfig.vite{{if eq .MODE "production"}}.production{{end}}.json'
    requires:
      vars:
        - name: MODE
          enum: [development, production]
    sources:
      - ./package.json
      - ./vite.config.ts
      - ./tsconfig/tsconfig.app.json
      - ./tsconfig/tsconfig.app.base.json
      - '{{.TSCONFIG}}'
      - ./src/**/*
    cmds:
      - bunx --no-install tsc --noEmit --project '{{.TSCONFIG}}'

  dev:
    vars:
      MODE:
        ref: .SWAPI_OUTPUT_MODE | default .MODE | default "development"
    requires:
      vars:
        - name: MODE
          enum: [development, production]
    deps:
      - task: :shared:generate
    dotenv:
      - ./.env/.env.target.local
      - ./.env/.env.output.{{.MODE}}
    cmds:
      - bunx --no-install vite --configLoader runner

  build:
    vars:
      MODE:
        ref: .SWAPI_OUTPUT_MODE | default .MODE | default "production"
      TARGET:
        ref: .SWAPI_TARGET | default .TARGET | default "local"
    requires:
      vars:
        - name: MODE
          enum: [development, production]
        - name: TARGET
          enum: [local, testing, production]
    deps:
      - task: build:browser
        vars:
          MODE: '{{.MODE}}'
          TARGET: '{{.TARGET}}'
      - task: build:ssr
        vars:
          MODE: '{{.MODE}}'
          TARGET: '{{.TARGET}}'

  build:browser:
    vars:
      MODE:
        ref: .SWAPI_OUTPUT_MODE | default .MODE | default "production"
      TARGET:
        ref: .SWAPI_TARGET | default .TARGET | default "local"
      BUILD_VARIANT_PATH: '{{.TARGET}}/{{.MODE}}'
      DIST_DIR: './dist/{{.BUILD_VARIANT_PATH}}/browser'
      TSCONFIG: './tsconfig/tsconfig.vite{{if eq .MODE "production"}}.production{{end}}.json'
    requires:
      vars:
        - name: MODE
          enum: [development, production]
        - name: TARGET
          enum: [local, pages, testing, production]
    deps:
      - task: build:dist-paths
        vars:
          MODE: '{{.MODE}}'
          TARGET: '{{.TARGET}}'
      - task: :shared:build
        vars:
          MODE: '{{.MODE}}'
    dotenv:
      - ./.env/.env.target.{{.TARGET}}
      - ./.env/.env.output.{{.MODE}}
    sources:
      - ./package.json
      - ./vite.config.ts
      - ./.env/.env.output.{{.MODE}}
      - ./.env/.env.target.{{.TARGET}}
      - ./tsconfig/tsconfig.app.json
      - ./tsconfig/tsconfig.app.base.json
      - '{{.TSCONFIG}}'
      - ./{src,public}/**/*
    generates:
      - '{{.DIST_DIR}}/**/*'
    cmds:
      - >
        bunx --no-install vite build
        --outDir '{{.DIST_DIR}}'

  build:ssr:
    vars:
      MODE:
        ref: .SWAPI_OUTPUT_MODE | default .MODE | default "production"
      TARGET:
        ref: .SWAPI_TARGET | default .TARGET | default "local"
      BUILD_VARIANT_PATH: '{{.TARGET}}/{{.MODE}}'
      DIST_DIR: './dist/{{.BUILD_VARIANT_PATH}}/ssr'
      TSCONFIG: './tsconfig/tsconfig.vite{{if eq .MODE "production"}}.production{{end}}.json'
    requires:
      vars:
        - name: MODE
          enum: [development, production]
        - name: TARGET
          enum: [local, testing, production]
    deps:
      - task: build:dist-paths
        vars:
          MODE: '{{.MODE}}'
          TARGET: '{{.TARGET}}'
      - task: :shared:build
        vars:
          MODE: '{{.MODE}}'
    dotenv:
      - ./.env/.env.target.{{.TARGET}}
      - ./.env/.env.output.{{.MODE}}
    sources:
      - ./package.json
      - ./vite.config.ts
      - ./.env/.env.output.{{.MODE}}
      - ./.env/.env.target.{{.TARGET}}
      - ./tsconfig/tsconfig.app.json
      - ./tsconfig/tsconfig.app.base.json
      - '{{.TSCONFIG}}'
      - ./{src,public}/**/*
    generates:
      - '{{.DIST_DIR}}/**/*'
    cmds:
      - >
        bunx --no-install vite build
        --ssr ./src/main.server.ts
        --outDir '{{.DIST_DIR}}'

  build:dist-paths:
    vars:
      MODE:
        ref: .SWAPI_OUTPUT_MODE | default .MODE | default "production"
      TARGET:
        ref: .SWAPI_TARGET | default .TARGET | default "local"
      BUILD_VARIANT_PATH: '{{.TARGET}}/{{.MODE}}'
      DIST_PATH: './dist/{{.BUILD_VARIANT_PATH}}'
    requires:
      vars:
        - name: MODE
          enum: [development, production]
        - name: TARGET
          enum: [local, testing, production]
    sources:
      - ./tsconfig/tsconfig.dist-paths.json
      - ./src/dist-paths.ts
    generates:
      - '{{.DIST_PATH}}/dist-paths.js'
    cmds:
      - >
        bunx --no-install tsc
        --project ./tsconfig/tsconfig.dist-paths.json
        --outDir '{{.DIST_PATH}}'

  start:
    vars:
      MODE:
        ref: .SWAPI_OUTPUT_MODE | default .MODE | default "production"
      TARGET:
        ref: .SWAPI_TARGET | default .TARGET | default "local"
      BUILD_VARIANT_PATH: '{{.TARGET}}/{{.MODE}}'
      DIST_DIR: './dist/{{.BUILD_VARIANT_PATH}}/browser'
    requires:
      vars:
        - name: MODE
          enum: [development, production]
        - name: TARGET
          enum: [local, testing, production]
    deps:
      - task: build:browser
        vars:
          MODE: '{{.MODE}}'
          TARGET: '{{.TARGET}}'
    dotenv:
      - ./.env/.env.target.{{.TARGET}}
      - ./.env/.env.output.{{.MODE}}
    cmds:
      - bunx --no-install vite preview --outDir '{{.DIST_DIR}}'

  test:
    deps:
      - task: :shared:build
        vars:
          MODE: development
    dotenv:
      - ./.env/.env.target.{{.TARGET}}
      - ./.env/.env.output.development
    cmds:
      - bunx --no-install vitest --configLoader runner run

  test:watch:
    deps:
      - task: :shared:build
        vars:
          MODE: development
    dotenv:
      - ./.env/.env.target.{{.TARGET}}
      - ./.env/.env.output.development
    interactive: true
    cmds:
      - bunx --no-install vitest --configLoader runner
