version: 3

tasks:
  clean:
    - rm -rf ./.cache || true
    - rm -rf ./.task || true
    - rm -rf ./dist || true

  lint:
    vars:
      PROFILE:
        ref: .SWAPI_PROFILE | default .PROFILE | default "debug"
      TSCONFIG: './tsconfig/tsconfig.vite{{if eq .PROFILE "release"}}.release{{end}}.json'
    requires:
      vars:
        - name: PROFILE
          enum: [debug, release]
    sources:
      - ./index.html
      - ./package.json
      - ./vite.config.ts
      - ./tsconfig/**/*.json
      - ./src/**/*.{ts,json}
      - ../../bun.lock
      - ../../../packages/shared/src/**/*.ts
    cmds:
      - bunx --no-install tsc --noEmit --project '{{.TSCONFIG}}'

  lint:a11y:
    sources:
      - ./index.html
      - ./package.json
      - ./vite.config.ts
      - ./tsconfig/**/*.json
      - ./src/**/*.{ts,json,html,css}
      - ../../bun.lock
      - ../../../packages/shared/src/**/*.ts
    cmds:
      - bunx axe http://localhost:4200 --tags wcag2a,wcag2aa,wcag21a,wcag21aa --exit

  dev:
    deps:
      - task: :shared:generate
    dotenv:
      - ./.env/.env.local.debug
    env:
      SWAPI_RUN_MODE: source
    cmds:
      - bunx --no-install vite dev --configLoader runner

  build:
    vars:
      PROFILE:
        ref: .SWAPI_PROFILE | default .PROFILE | default "release"
      TARGET:
        ref: .SWAPI_TARGET | default .TARGET | default "local"
    requires:
      vars:
        - name: PROFILE
          enum: [debug, release]
        - name: TARGET
          enum: [local, testing, production]
    deps:
      - task: build:browser
        vars:
          PROFILE: '{{.PROFILE}}'
          TARGET: '{{.TARGET}}'
      - task: build:ssr
        vars:
          PROFILE: '{{.PROFILE}}'
          TARGET: '{{.TARGET}}'

  build:browser:
    vars:
      PROFILE:
        ref: .SWAPI_PROFILE | default .PROFILE | default "release"
      TARGET:
        ref: .SWAPI_TARGET | default .TARGET | default "local"
      VARIANT_PATH: '{{.TARGET}}/{{.PROFILE}}'
      DIST_DIR: './dist/{{.VARIANT_PATH}}/browser'
      TSCONFIG: './tsconfig/tsconfig.vite{{if eq .PROFILE "release"}}.release{{end}}.json'
    requires:
      vars:
        - name: PROFILE
          enum: [debug, release]
        - name: TARGET
          enum: [local, pages, testing, production]
    deps:
      - task: build:dist-paths
        vars:
          PROFILE: '{{.PROFILE}}'
          TARGET: '{{.TARGET}}'
      - task: :shared:build
        vars:
          PROFILE: '{{.PROFILE}}'
    dotenv:
      - ./.env/.env.{{.TARGET}}.{{.PROFILE}}
    env:
      SWAPI_RUN_MODE: build
    sources:
      - ./index.html
      - ./package.json
      - ./vite.config.ts
      - ./.env/.env.{{.TARGET}}.{{.PROFILE}}
      - ./tsconfig/tsconfig.app.json
      - ./tsconfig/tsconfig.app.base.json
      - '{{.TSCONFIG}}'
      - ./{src,public}/**/*
      - ../../bun.lock
    generates:
      - '{{.DIST_DIR}}/**/*'
    cmds:
      - >
        bunx --no-install vite build
        --outDir '{{.DIST_DIR}}'

  build:ssr:
    vars:
      PROFILE:
        ref: .SWAPI_PROFILE | default .PROFILE | default "release"
      TARGET:
        ref: .SWAPI_TARGET | default .TARGET | default "local"
      VARIANT_PATH: '{{.TARGET}}/{{.PROFILE}}'
      DIST_DIR: './dist/{{.VARIANT_PATH}}/ssr'
      TSCONFIG: './tsconfig/tsconfig.vite{{if eq .PROFILE "release"}}.release{{end}}.json'
    requires:
      vars:
        - name: PROFILE
          enum: [debug, release]
        - name: TARGET
          enum: [local, testing, production]
    deps:
      - task: build:dist-paths
        vars:
          PROFILE: '{{.PROFILE}}'
          TARGET: '{{.TARGET}}'
      - task: :shared:build
        vars:
          PROFILE: '{{.PROFILE}}'
    dotenv:
      - ./.env/.env.{{.TARGET}}.{{.PROFILE}}
    env:
      SWAPI_RUN_MODE: build
    sources:
      - ./index.html
      - ./package.json
      - ./vite.config.ts
      - ./.env/.env.{{.TARGET}}.{{.PROFILE}}
      - ./tsconfig/tsconfig.app.json
      - ./tsconfig/tsconfig.app.base.json
      - '{{.TSCONFIG}}'
      - ./{src,public}/**/*
      - ../../bun.lock
    generates:
      - '{{.DIST_DIR}}/**/*'
    cmds:
      - >
        bunx --no-install vite build
        --ssr ./src/main.server.ts
        --outDir '{{.DIST_DIR}}'

  build:dist-paths:
    vars:
      PROFILE:
        ref: .SWAPI_PROFILE | default .PROFILE | default "release"
      TARGET:
        ref: .SWAPI_TARGET | default .TARGET | default "local"
      VARIANT_PATH: '{{.TARGET}}/{{.PROFILE}}'
      DIST_PATH: './dist/{{.VARIANT_PATH}}'
    requires:
      vars:
        - name: PROFILE
          enum: [debug, release]
        - name: TARGET
          enum: [local, pages, testing, production]
    sources:
      - ./tsconfig/tsconfig.dist-paths.json
      - ./src/dist-paths.ts
      - ../../bun.lock
    generates:
      - '{{.DIST_PATH}}/dist-paths.js'
    cmds:
      - >
        bunx --no-install tsc
        --project ./tsconfig/tsconfig.dist-paths.json
        --outDir '{{.DIST_PATH}}'

  start:
    vars:
      PROFILE:
        ref: .SWAPI_PROFILE | default .PROFILE | default "release"
      TARGET:
        ref: .SWAPI_TARGET | default .TARGET | default "local"
      VARIANT_PATH: '{{.TARGET}}/{{.PROFILE}}'
      DIST_DIR: './dist/{{.VARIANT_PATH}}/browser'
    requires:
      vars:
        - name: PROFILE
          enum: [debug, release]
        - name: TARGET
          enum: [local, testing, production]
    deps:
      - task: build:browser
        vars:
          PROFILE: '{{.PROFILE}}'
          TARGET: '{{.TARGET}}'
    dotenv:
      - ./.env/.env.{{.TARGET}}.{{.PROFILE}}
    env:
      SWAPI_RUN_MODE: build
    cmds:
      - bunx --no-install vite preview --outDir '{{.DIST_DIR}}'

  test:
    deps:
      - task: :shared:build
        vars:
          PROFILE: debug
    dotenv:
      - ./.env/.env.local.debug
    env:
      SWAPI_RUN_MODE: source
    cmds:
      - bunx --no-install vitest --configLoader runner run

  test:watch:
    deps:
      - task: :shared:build
        vars:
          PROFILE: debug
    dotenv:
      - ./.env/.env.local.debug
    env:
      SWAPI_RUN_MODE: source
    interactive: true
    cmds:
      - bunx --no-install vitest --configLoader runner
