version: '3'
run: once
set: [pipefail]

# TODO: Eigentlich muss shared gebaut werden. Sollte ich das shared Taskfile jeweils importieren
# oder doch alles in einem Task file zusammen bauen?
tasks:
  dev:
    cmds:
      - bunx --no-install vite --config ./vite.config.ts

  dev:ssr:
    cmds:
      - >
        bunx --no-install vite build
        --mode development
        --config ./vite.config.ts
        --ssr ./main.server.ts
        --outDir ../dist/local/development/ssr
        --watch
        --emptyOutDir

  build:
    deps:
      - task: build:prod
      - task: build:prod:ssr

  build:prod:
    cmds:
      - >
        bunx --no-install vite build
        --config ./vite.config.ts
        --outDir ../dist/production/production/browser
        --emptyOutDir

  build:prod:ssr:
    cmds:
      - >
        bunx --no-install vite build
        --config ./vite.config.ts
        --ssr ./main.server.ts
        --outDir ../dist/production/production/ssr
        --emptyOutDir

  test:
    cmds:
      - bunx --no-install vitest run

  test:watch:
    cmds:
      - bunx --no-install vitest
