version: 3

tasks:
  clean:
    cmds:
      - rm -f ./*.tsbuildinfo || true
      - rm -rf ./cache || true
      - rm -rf ./dist || true
      - rm -rf ./generated || true

  build:
    deps:
      - task: generate
    preconditions:
      - test -s ./tsconfig.shared.production.json
    sources:
      - ./src/**/*
    generates:
      - ./dist/**/*
    cmds:
      - bunx --no-install tsc --project ./tsconfig.shared.production.json

  generate:
    deps:
      - task: generate:device-cookie:types
      - task: generate:device-cookie:validator
      - task: generate:custom-media-tokens

  generate:device-cookie:types:
    sources:
      - ./generators/device-cookie.schema.json
    generates:
      - ./generated/types/device-cookie.types.d.ts
    cmds:
      - mkdir -p ./generated/types
      - >
        bunx --no-install quicktype
        --src ./generators/device-cookie.schema.json
        --src-lang schema
        --lang typescript
        --nice-property-names
        --readonly
        --top-level DeviceCookie
        --just-types
        --out ./generated/types/device-cookie.types.d.ts

  generate:device-cookie:validator:
    sources:
      - ./generators/device-cookie.schema.json
      - ./generators/device-cookie.validator.*
    generates:
      - ./generated/validators/device-cookie.*
    cmds:
      - >
        bunx --no-install bun
        --conditions @swapi/source
        ./generators/device-cookie.validator.generator.ts

  generate:custom-media-tokens:
    sources:
      - ./generators/custom-media-tokens.*
      - ./src/device/context.ts
    generates:
      - ./generated/css/media.css
    cmds:
      - >
        bunx --no-install bun
        --conditions @swapi/source
        ./generators/custom-media-tokens.generator.ts

  lint:
    deps:
      - task: lint:generators
      - task: lint:shared

  lint:generators:
    vars:
      MODE:
        ref: .SWAPI_OUTPUT_MODE | default .MODE | default "development"
      TSCONFIG: './tsconfig.generators{{if eq .MODE "production"}}.production{{end}}.json'
    requires:
      vars:
        - name: MODE
          enum: [development, production]
    sources:
      - '{{.TSCONFIG}}'
      - ./{generators,src}/**/*
    cmds:
      - bunx --no-install tsc --noEmit --project '{{.TSCONFIG}}'

  lint:shared:
    vars:
      MODE:
        ref: .SWAPI_OUTPUT_MODE | default .MODE | default "development"
      TSCONFIG: './tsconfig.shared{{if eq .MODE "production"}}.production{{end}}.json'
    requires:
      vars:
        - name: MODE
          enum: [development, production]
    sources:
      - '{{.TSCONFIG}}'
      - ./src/**/*
    cmds:
      - bunx --no-install tsc --noEmit --project '{{.TSCONFIG}}'
