version: 3

tasks:
  clean:
    preconditions:
      - test -s ./tsconfig.shared.json
    cmds:
      - rm -f ./tsconfig.shared.tsbuildinfo || true
      - rm -rf ./dist || true
      - rm -rf ./generated || true

  build:
    deps:
      - task: generate
    preconditions:
      - test -s ./tsconfig.shared.json
    sources:
      - ./src/**/*
    generates:
      - ./dist/**/*
    cmds:
      - rm -f ./tsconfig.shared.tsbuildinfo || true
      - rm -rf ./dist || true
      - bunx --no-install tsc -p ./tsconfig.shared.json

  generate:
    deps:
      - task: generate:device-cookie:types
      - task: generate:device-cookie:validator
      - task: generate:postcss-media-tokens

  generate:device-cookie:types:
    sources:
      - ./generators/device-cookie.schema.json
    generates:
      - ./generated/types/device-cookie.types.d.ts
    cmds:
      - rm -rf ./generated/types || true
      - mkdir -p ./generated/types
      - >
        bunx --no-install quicktype
        --src ./generators/device-cookie.schema.json
        --src-lang schema
        --lang typescript
        --nice-property-names
        --readonly
        --top-level DeviceCookie
        --just-types
        --out ./generated/types/device-cookie.types.d.ts

  generate:device-cookie:validator:
    sources:
      - ./generators/device-cookie.schema.json
      - ./generators/device-cookie.validator.*
    generates:
      - ./generated/validators/device-cookie.*
    cmds:
      - rm -rf ./generated/validators || true
      - mkdir -p ./generated/validators
      - >
        bunx --no-install bun
        --conditions @swapi/source
        ./generators/device-cookie.validator.generator.ts

  generate:postcss-media-tokens:
    sources:
      - ./generators/postcss-media-tokens.*
      - ./src/device/context.ts
    generates:
      - ./generated/css/media.css
    cmds:
      - rm -rf ./generated/css || true
      - mkdir -p ./generated/css
      - >
        bunx --no-install bun
        --conditions @swapi/source
        ./generators/postcss-media-tokens.generator.ts
