version: 3

tasks:
  clean:
    cmds:
      - rm -f ./tsconfig/*.tsbuildinfo || true
      - rm -rf ./.cache || true
      - rm -rf ./.task || true
      - rm -rf ./dist || true
      - rm -rf ./generated || true

  lint:tsc:
    deps:
      - task: lint:tsc:generators
      - task: lint:tsc:src

  lint:tsc:generators:
    sources:
      - './package.json'
      - './generators/**/*.{ts,json}'
      - './src/**/*.ts'
      - './tsconfig/**/*.json'
      - '{{.SOURCES.tsconfigPackage}}'
      - '{{.SOURCES.tsconfigs}}'
      - '{{.SOURCES.lockfile}}'
    cmds:
      - bunx --no-install tsc --noEmit --project ./tsconfig/tsconfig.generators.json

  lint:tsc:src:
    sources:
      - './package.json'
      - './src/**/*.ts'
      - './tsconfig/**/*.json'
      - '{{.SOURCES.tsconfigPackage}}'
      - '{{.SOURCES.tsconfigs}}'
      - '{{.SOURCES.lockfile}}'
    cmds:
      - bunx --no-install tsc --noEmit --project ./tsconfig/tsconfig.shared.json

  build:
    label: '{{.TASK}}:{{.BUILD_PROFILE}}'
    requires:
      vars:
        - name: BUILD_PROFILE
          enum: [development, release]
    vars:
      DIST_DIR: './dist/{{.BUILD_PROFILE}}'
      TSCONFIGS:
        map:
          development: ./tsconfig/tsconfig.shared.json
          release: ./tsconfig/tsconfig.shared.release.json
      TSCONFIG: '{{get .TSCONFIGS .BUILD_PROFILE}}'
    sources:
      - './package.json'
      - './src/**/*'
      - './tsconfig/**/*.json'
      - '{{.SOURCES.lockfile}}'
    generates:
      - '{{.DIST_DIR}}/**/*'
    deps:
      - task: generate
    cmds:
      - bunx --no-install tsc --project {{.TSCONFIG | q}} --outDir {{.DIST_DIR | q}}

  generate:
    deps:
      - task: generate:device-cookie:types
      - task: generate:device-cookie:validator
      - task: generate:custom-media-tokens

  generate:device-cookie:types:
    sources:
      - './generators/device-cookie.schema.json'
      - '{{.SOURCES.lockfile}}'
    generates:
      - './generated/types/device-cookie.types.d.ts'
    cmds:
      - mkdir -p ./generated/types || true
      - >
        bunx --no-install quicktype
        --src ./generators/device-cookie.schema.json
        --src-lang schema
        --lang typescript
        --nice-property-names
        --readonly
        --top-level DeviceCookie
        --just-types
        --out ./generated/types/device-cookie.types.d.ts

  generate:device-cookie:validator:
    sources:
      - './generators/device-cookie.schema.json'
      - './generators/device-cookie.validator.*'
      - '{{.SOURCES.lockfile}}'
    generates:
      - './generated/validators/device-cookie.*'
    cmds:
      - >
        bunx --no-install bun
        --conditions @swapi/shared/source
        ./generators/device-cookie.validator.generator.ts

  generate:custom-media-tokens:
    sources:
      - './generators/custom-media-tokens.*'
      - './src/device/device.ts'
      - '{{.SOURCES.lockfile}}'
    generates:
      - './generated/css/media.css'
    cmds:
      - >
        bunx --no-install bun
        --conditions @swapi/shared/source
        ./generators/custom-media-tokens.generator.ts
