version: 3

vars:
  DIN_PLAYWRIGHT: swapi-platform-playwright

tasks:
  clean:
    dotenv:
      - ./.env/.env.local
    env:
      NODE_OPTIONS: --conditions=@swapi/shared/source
    cmds:
      - rm -rf ./.task || true
      - rm -rf ./test-results || true
      - rm -rf ./playwright-report || true
      - bunx --no-install playwright clear-cache

  install:
    preconditions:
      - command -v npx
    cmds:
      - npx playwright install chromium

  lint:tsc:
    sources:
      - './package.json'
      - './playwright.config.ts'
      - './src/**/*.ts'
      - './tsconfig/**/*.json'
      - '{{.ROOT_DIR}}/packages/shared/package.json'
      - '{{.ROOT_DIR}}/packages/shared/src/**/*.ts'
      - '{{.SOURCES.tsconfigPackage}}'
      - '{{.SOURCES.tsconfigs}}'
      - '{{.SOURCES.lockfile}}'
    cmds:
      - bunx --no-install tsc --noEmit --project ./tsconfig/tsconfig.e2e.json

  build:deps:
    deps:
      - task: :shared:build

  build:docker:
    requires:
      vars:
        - name: DOCKER_TARGET
          enum: [runtime, base, deps, browsers, code]
    vars:
      IMAGE_TAG: '{{.DIN_PLAYWRIGHT}}:local'
    dotenv:
      - './.env/.env.ci'
    cmds:
      - >
        docker buildx build
        --load
        --file ./Dockerfile.e2e
        {{if ne .DOCKER_TARGET "runtime"}}
        --target {{.DOCKER_TARGET}}
        {{end}}
        --tag {{.IMAGE_TAG}}
        {{.ROOT_DIR}}

  start:docker:
    interactive: true
    requires:
      vars:
        - name: DEV_MODE
          enum: ['true', 'false']
    dotenv:
      - './.env/.env.local'
    cmds:
      - >
        docker run
        {{if ne .DEV_MODE "true"}}
        --detach
        {{end}}
        {{if eq .DEV_MODE "true"}}
        --interactive
        --tty
        --entrypoint bash
        {{end}}
        --rm
        --init
        --ipc=host
        --publish ${PORT}:${PORT}
        --ulimit nofile=65536:65536
        --ulimit core=0:0
        --name={{.DIN_PLAYWRIGHT}}
        {{.DIN_PLAYWRIGHT}}:local
        {{if ne .DEV_MODE "true"}}
        test
        {{end}}

  test:
    dotenv:
      - './.env/.env.local'
    env:
      NODE_OPTIONS: --conditions=@swapi/shared/source
    deps:
      - task: build:deps
    cmds:
      - >
        bunx --no-install playwright test
        --max-failures 1
        --forbid-only
        --fail-on-flaky-tests
        {{.CLI_ARGS}}

  update-screenshots:
    cmds:
      - task: test
        vars:
          CLI_ARGS: --grep '@screenshot' --update-snapshots --no-deps

  codegen:
    desc: 'Requires server bundle to be ran manually atm.'
    dotenv:
      - './.env/.env.local'
    env:
      NODE_OPTIONS: --conditions=@swapi/shared/source
    deps:
      - task: build:deps
      - task: :server:build:bundle
    cmds:
      - bunx --no-install playwright codegen localhost:51000
