name: swapi-platform

x-build-args-common: &build-args-common
  NODE_VERSION: 24.16.0
  BUN_VERSION: 1.3.14
  SWAPI_GIT_COMMIT_SHA: ${SWAPI_GIT_COMMIT_SHA:?GIT_SHA is required}

services:
  app-server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile.app-server
      target: ${DOCKER_TARGET}
      args:
        <<: *build-args-common
        NODE_ENV: ${NODE_ENV}
        SWAPI_BUILD_LEVEL: ${SWAPI_BUILD_LEVEL}
        SWAPI_TARGET_ENVIRONMENT: ${SWAPI_TARGET_ENVIRONMENT}
        DOCKER_RUNTIME_IMAGE_VARIANT: ${DOCKER_RUNTIME_IMAGE_VARIANT}
      tags:
        - ${IMAGE_TAG}
    image: ${IMAGE_TAG}
    container_name: ${APP_SERVER_CONTAINER_NAME}
    env_file: ${APP_SERVER_ENV_FILE}
    environment:
      NODE_ENV: ${NODE_ENV}
      SWAPI_BUILD_LEVEL: ${SWAPI_BUILD_LEVEL}
      SWAPI_TARGET_ENVIRONMENT: ${SWAPI_TARGET_ENVIRONMENT}
    ports:
      - ${SWAPI_SERVER_PORT}:${SWAPI_SERVER_PORT}
    healthcheck:
      test:
        - CMD
        - curl
        - --fail
        - --head
        - http://localhost:${SWAPI_SERVER_PORT}/health/ready
      start_period: 15s
      start_interval: 3s
      timeout: 2s
      interval: 1m
      retries: 1
    init: true

  # app-worker:
  #   environment:
  #     TARGET_ENVIRONMENT: local
  #   build:
  #     context: .
  #     dockerfile: ./packages/worker/Dockerfile.app-worker
  #     target: runtime
  #     tags:
  #       - 'swapi-platform-app-worker:local'
  #   init: true
  #   # cpu_percent: 20
  #   # cpu_count: 2
  #   # cpu_shares: 3
  #   ulimits:
  #     # nproc: 128
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #     core:
  #       soft: 0
  #       hard: 0
  #     memlock:
  #       soft: 0
  #       hard: 0
  #   # entrypoint: ["executable", "arg"]
  #   # wip
  #   command: >
  #       dev
  #       --env local
  #       --no-bundle
  #       --ip 0.0.0.0
  #       --port 52000
  #       ./index.js
  #   ports:
  #     - '52000:52000'
  #   depends_on:
  #     app-server:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ['CMD', 'curl', '--fail', '--head', 'http://localhost:52000/health/ready']
  #     start_period: 10s
  #     start_interval: 1s
  #     timeout: 500ms
  #     interval: 1m
  #     retries: 1

  # e2e:
  #   build:
  #     context: .
  #     dockerfile: ./packages/e2e/Dockerfile.e2e
  #   depends_on:
  #     app-server:
  #       condition: service_healthy
  #     app-worker:
  #       condition: service_healthy
  #   env_file:
  #     - './.env/.env.local'
