version: 3

run: when_changed
set:
  - pipefail
  - errexit
shopt:
  - globstar
output: prefixed

vars:
  T_GIT_COMMIT_SHA:
    sh: |
      if command -v git >/dev/null 2>&1; then
        printf "%s" "$(git rev-parse --verify HEAD)"
      fi
  T_SOURCES:
    map:
      lockfile: '{{.ROOT_DIR}}/bun.lock'
      tsconfigPackage: '{{.ROOT_DIR}}/packages/tsconfig/package.json'
      tsconfigs: '{{.ROOT_DIR}}/packages/tsconfig/src/**/*.json'

includes:
  dev:
    taskfile: ./Taskfile.local.yml
    optional: true
    flatten: true
  tools:
    taskfile: ./Taskfile.tools.yml
    dir: ./
  client:
    taskfile: ./packages/client
    dir: ./packages/client
  e2e:
    taskfile: ./packages/e2e
    dir: ./packages/e2e
  hono:
    taskfile: ./packages/hono
    dir: ./packages/hono
  server:
    taskfile: ./packages/server
    dir: ./packages/server
  server:fly:
    taskfile: ./packages/server/Taskfile.fly.yml
    dir: ./packages/server
  shared:
    taskfile: ./packages/shared
    dir: ./packages/shared
  worker:
    taskfile: ./packages/worker
    dir: ./packages/worker

tasks:
  clean:
    cmds:
      - task: client:clean
      - task: e2e:clean
      - task: hono:clean
      - task: server:clean
      - task: shared:clean
      - task: worker:clean
      - rm -rf ./.cache || true

  install:
    aliases:
      - i
    preconditions:
      - command -v bun
    cmds:
      - bun install --link-native-bins
      - task: e2e:install

  lint:
    deps:
      - task: lint:code
      - task: lint:docker
      - task: lint:format

  lint:code:
    cmds:
      - task: tools:tsc:lint
      - task: tools:eslint:lint

  lint:docker:
    cmds:
      - task: tools:tally:lint

  lint:format:
    cmds:
      - task: tools:prettier:lint

  fix:
    deps:
      - task: fix:code
      - task: fix:docker
      - task: fix:format

  fix:code:
    cmds:
      - task: tools:eslint:fix

  fix:docker:
    cmds:
      - task: tools:tally:fix

  fix:format:
    cmds:
      - task: tools:prettier:fix
