version: 3
run: once
set: [pipefail]
output: prefixed

includes:
  client:
    taskfile: ./packages/client
    dir: ./packages/client
  server:
    taskfile: ./packages/server
    dir: ./packages/server
  shared:
    taskfile: ./packages/shared
    dir: ./packages/shared

tasks:
  clean:
    cmds:
      - task: client:clean
      - task: shared:clean
      - task: server:clean
  lint:
    cmds:
      - task: lint:tsc
      - task: lint:eslint
      - task: lint:prettier

  lint:tsc:
    deps:
      - task: lint:tsc:client
      - task: lint:tsc:server
      - task: lint:tsc:shared

  lint:tsc:client:
    cmds:
      - bunx --no-install tsc --noEmit --project ./packages/client/tsconfig.app.json

  lint:tsc:server:
    cmds:
      - bunx --no-install tsc --noEmit --project ./packages/server/tsconfig.server.json

  lint:tsc:shared:
    cmds:
      - bunx --no-install tsc --noEmit --project ./packages/shared/tsconfig.shared.json

  lint:eslint:
    cmds:
      - bunx --no-install eslint .

  lint:prettier:
    cmds:
      - bunx --no-install prettier --check .

  fix:
    cmds:
      - bunx --no-install eslint . --fix
      - task: format

  format:
    cmds:
      - bunx --no-install prettier --write --list-different .
