version: 3

tasks:
  clean:
    cmds:
      - rm -f ./tsconfig/*.tsbuildinfo || true
      - rm -rf ./dist || true

  lint:tsc:
    sources:
      - './package.json'
      - './src/**/*.ts'
      - './tsconfig/**/*.json'
      - '{{.ROOT_DIR}}/packages/shared/package.json'
      - '{{.ROOT_DIR}}/packages/shared/src/**/*.ts'
      - '{{.SOURCES.tsconfigPackage}}'
      - '{{.SOURCES.tsconfigs}}'
      - '{{.SOURCES.lockfile}}'
    cmds:
      - bunx --no-install tsc --noEmit --project ./tsconfig/tsconfig.hono.json

  build:
    label: '{{.TASK}}@{{.BUILD_PROFILE}}'
    requires:
      vars:
        - name: BUILD_PROFILE
          enum: [development, release]
    vars:
      TSCONFIGS:
        map:
          development: ./tsconfig/tsconfig.hono.json
          release: ./tsconfig/tsconfig.hono.release.json
      TSCONFIG: '{{get .TSCONFIGS .BUILD_PROFILE}}'
      DIST_DIR: './dist/{{.BUILD_PROFILE}}'
    sources:
      - './package.json'
      - './src/**/*'
      - './tsconfig/**/*.json'
      - '{{.SOURCES.lockfile}}'
    generates:
      - '{{.DIST_DIR}}/**/*'
    deps:
      - task: :shared:build
        vars:
          BUILD_PROFILE: '{{.BUILD_PROFILE}}'
    cmds:
      - bunx --no-install tsc --project {{.TSCONFIG | q}} --outDir {{.DIST_DIR | q}}
