version: 3

tasks:
  clean:
    cmds:
      - rm -f ./tsconfig/*.tsbuildinfo || true
      - rm -rf ./.cache || true
      - rm -rf ./.task || true
      - rm -rf ./dist || true

  lint:
    vars:
      PROFILE:
        ref: .SWAPI_PROFILE | default .PROFILE | default "debug"
      TSCONFIG: './tsconfig/tsconfig.server{{if eq .PROFILE "release"}}.release{{end}}.json'
    requires:
      vars:
        - name: PROFILE
          enum: [debug, release]
    deps:
      - task: :shared:generate
    sources:
      - '{{.TSCONFIG}}'
      - ./src/**/*
      - ./docker/**/*
      - ../../bun.lock
    cmds:
      - bunx --no-install tsc --noEmit --project '{{.TSCONFIG}}'

  dev:
    vars:
      PROFILE:
        ref: .SWAPI_PROFILE | default .PROFILE | default "debug"
    requires:
      vars:
        - name: PROFILE
          enum: [debug, release]
    deps:
      - task: :client:build
        vars:
          PROFILE: '{{.PROFILE}}'
          TARGET: local
    dotenv:
      - ./.env/.env.local.{{.PROFILE}}
    env:
      SWAPI_RUN_MODE: source
    interactive: true
    cmds:
      - >
        bunx --no-install bun
        --conditions @swapi/shared/source
        --conditions @swapi/server/source
        --conditions @swapi/local/{{.PROFILE}}
        --watch ./src/server.jit.ts

  build:with-ssg:
    vars:
      PROFILE:
        ref: .SWAPI_PROFILE | default .PROFILE | default "release"
      TARGET:
        ref: .SWAPI_TARGET | default .TARGET | default "local"
      VARIANT_PATH: '{{.TARGET}}/{{.PROFILE}}'
      BUILD_DIST_DIR: './dist/{{.VARIANT_PATH}}/build'
      TARGET_AND_PROFILE_CONDITION: '@swapi/{{.VARIANT_PATH}}'
      PROFILE_CONDITION: '@swapi/{{.PROFILE}}'
      TSCONFIG: './tsconfig/tsconfig.server{{if eq .PROFILE "release"}}.release{{end}}.json'
      CLIENT_DIST_ROOT: '../client/dist/{{.VARIANT_PATH}}'
      CLIENT_SSG_DIST_DIR: '{{.CLIENT_DIST_ROOT}}/ssg'
      CLIENT_SSR_ENTRY: '{{.CLIENT_DIST_ROOT}}/ssr/main.server.js'
    requires:
      vars:
        - name: PROFILE
          enum: [debug, release]
        - name: TARGET
          enum: [local, testing, production]
    deps:
      - task: build
        vars:
          PROFILE: '{{.PROFILE}}'
          TARGET: '{{.TARGET}}'
    dotenv:
      - ./.env/.env.{{.TARGET}}.{{.PROFILE}}
    env:
      SWAPI_RUN_MODE: build
    sources:
      - '{{.TSCONFIG}}'
      - ./package.json
      - ./.env/.env.{{.TARGET}}.{{.PROFILE}}
      - '{{.BUILD_DIST_DIR}}/ssg/render.js'
      - '{{.CLIENT_DIST_ROOT}}/browser/**/*'
      - '{{.CLIENT_DIST_ROOT}}/dist-paths.*'
      - '{{.CLIENT_DIST_ROOT}}/ssr/**/*'
      - ../../bun.lock
    generates:
      - '{{.CLIENT_SSG_DIST_DIR}}/index.html'
      - '{{.CLIENT_SSG_DIST_DIR}}/**/*/index.html'
    cmds:
      - >
        bunx --no-install bun
        --conditions {{.TARGET_AND_PROFILE_CONDITION}}
        --conditions {{.PROFILE_CONDITION}}
        {{.BUILD_DIST_DIR}}/ssg/render.js

  build:
    vars:
      PROFILE:
        ref: .SWAPI_PROFILE | default .PROFILE | default "release"
      TARGET:
        ref: .SWAPI_TARGET | default .TARGET | default "local"
    requires:
      vars:
        - name: PROFILE
          enum: [debug, release]
        - name: TARGET
          enum: [local, testing, production]
    deps:
      - task: build:compile
        vars:
          PROFILE: '{{.PROFILE}}'
          TARGET: '{{.TARGET}}'
      - task: :client:build
        vars:
          PROFILE: '{{.PROFILE}}'
          TARGET: '{{.TARGET}}'

  build:compile:
    vars:
      PROFILE:
        ref: .SWAPI_PROFILE | default .PROFILE | default "release"
      TARGET:
        ref: .SWAPI_TARGET | default .TARGET | default "local"
      VARIANT_PATH: '{{.TARGET}}/{{.PROFILE}}'
      BUILD_DIST_DIR: './dist/{{.VARIANT_PATH}}/build'
      TSCONFIG: './tsconfig/tsconfig.server{{if eq .PROFILE "release"}}.release{{end}}.json'
    requires:
      vars:
        - name: PROFILE
          enum: [debug, release]
        - name: TARGET
          enum: [local, testing, production]
    deps:
      - task: :shared:build
        vars:
          PROFILE: '{{.PROFILE}}'
    dotenv:
      - ./.env/.env.{{.TARGET}}.{{.PROFILE}}
    env:
      SWAPI_RUN_MODE: build
    sources:
      - '{{.TSCONFIG}}'
      - ./package.json
      - ./.env/.env.{{.TARGET}}.{{.PROFILE}}
      - ./src/**/*
      - ../../bun.lock
    generates:
      - '{{.BUILD_DIST_DIR}}/**/*'
    cmds:
      - >
        bunx --no-install tsc
        --project '{{.TSCONFIG}}'
        --outDir '{{.BUILD_DIST_DIR}}'

  build:bundle:
    vars:
      PROFILE:
        ref: .SWAPI_PROFILE | default .PROFILE | default "release"
      TARGET:
        ref: .SWAPI_TARGET | default .TARGET | default "local"
      VARIANT_PATH: '{{.TARGET}}/{{.PROFILE}}'
      DIST_ROOT: './dist/{{.VARIANT_PATH}}'
      BUILD_DIST_DIR: '{{.DIST_ROOT}}/build'
      BUNDLE_DIST_DIR: '{{.DIST_ROOT}}/bundle'
      TARGET_AND_PROFILE_CONDITION: '@swapi/{{.VARIANT_PATH}}'
      PROFILE_CONDITION: '@swapi/{{.PROFILE}}'
    requires:
      vars:
        - name: PROFILE
          enum: [debug, release]
        - name: TARGET
          enum: [local, testing, production]
    deps:
      - task: build:with-ssg
        vars:
          PROFILE: '{{.PROFILE}}'
          TARGET: '{{.TARGET}}'
    dotenv:
      - ./.env/.env.{{.TARGET}}.{{.PROFILE}}
    env:
      SWAPI_RUN_MODE: build
    sources:
      - ./tsconfig/tsconfig.server.bundle.json
      - ./rolldown.config.ts
      - ./docker/**/*.ts
      - '{{.BUILD_DIST_DIR}}/**/*'
      - ../../bun.lock
    generates:
      - '{{.BUNDLE_DIST_DIR}}/**/*'
    cmds:
      - >
        bunx --no-install bun
        --conditions {{.TARGET_AND_PROFILE_CONDITION}}
        --conditions {{.PROFILE_CONDITION}}
        "$(bunx --no-install bun pm bin)/rolldown"
        --config

  start:
    vars:
      PROFILE:
        ref: .SWAPI_PROFILE | default .PROFILE | default "release"
      TARGET:
        ref: .SWAPI_TARGET | default .TARGET | default "local"
      VARIANT_PATH: '{{.TARGET}}/{{.PROFILE}}'
      BUILD_DIST_DIR: './dist/{{.VARIANT_PATH}}/build'
      TARGET_AND_PROFILE_CONDITION: '@swapi/{{.VARIANT_PATH}}'
      PROFILE_CONDITION: '@swapi/{{.PROFILE}}'
    requires:
      vars:
        - name: PROFILE
          enum: [debug, release]
        - name: TARGET
          enum: [local, testing, production]
    deps:
      - task: build:with-ssg
        vars:
          PROFILE: '{{.PROFILE}}'
          TARGET: '{{.TARGET}}'
    dotenv:
      - ./.env/.env.{{.TARGET}}.{{.PROFILE}}
    env:
      SWAPI_RUN_MODE: build
    cmds:
      - >
        bunx --no-install bun
        --conditions {{.TARGET_AND_PROFILE_CONDITION}}
        --conditions {{.PROFILE_CONDITION}}
        {{.BUILD_DIST_DIR}}/server.jit.js

  start:bundle:
    vars:
      PROFILE:
        ref: .SWAPI_PROFILE | default .PROFILE | default "release"
      TARGET:
        ref: .SWAPI_TARGET | default .TARGET | default "local"
      VARIANT_PATH: '{{.TARGET}}/{{.PROFILE}}'
      BUNDLE_DIST_DIR: './dist/{{.VARIANT_PATH}}/bundle'
      TARGET_AND_PROFILE_CONDITION: '@swapi/{{.VARIANT_PATH}}'
      PROFILE_CONDITION: '@swapi/{{.PROFILE}}'
    requires:
      vars:
        - name: PROFILE
          enum: [debug, release]
        - name: TARGET
          enum: [local, testing, production]
    deps:
      - task: build:bundle
        vars:
          PROFILE: '{{.PROFILE}}'
          TARGET: '{{.TARGET}}'
    dotenv:
      - ./.env/.env.{{.TARGET}}.{{.PROFILE}}
    env:
      SWAPI_RUN_MODE: build
    cmds:
      - >
        bunx --no-install bun
        --conditions {{.TARGET_AND_PROFILE_CONDITION}}
        --conditions {{.PROFILE_CONDITION}}
        {{.BUNDLE_DIST_DIR}}/server.js
