version: 3

vars:
  DIN_APP_WORKER: swapi-platform-app-worker

tasks:
  clean:
    cmds:
      - rm -f ./tsconfig/*.tsbuildinfo || true
      - rm -rf ./.wrangler || true
      - rm -rf ./dist || true

  lint:tsc:
    sources:
      - './package.json'
      - './worker-configuration.d.ts'
      - './wrangler.jsonc'
      - './src/**/*.ts'
      - './tsconfig/**/*.json'
      - '{{.ROOT_DIR}}/packages/shared/package.json'
      - '{{.ROOT_DIR}}/packages/shared/generated/**/*.d.ts'
      - '{{.ROOT_DIR}}/packages/shared/src/**/*.ts'
      - '{{.ROOT_DIR}}/packages/hono/package.json'
      - '{{.ROOT_DIR}}/packages/hono/src/**/*.ts'
      - '{{.SOURCES.tsconfigPackage}}'
      - '{{.SOURCES.tsconfigs}}'
      - '{{.SOURCES.lockfile}}'
    deps:
      - task: typegen
      - task: :shared:generate
    cmds:
      - bunx --no-install tsc --noEmit --project ./tsconfig/tsconfig.worker.json

  typegen:
    cmds:
      - cmd: >
          bunx --no-install wrangler types
          --env-interface CloudflareBindings
        if: >
          ! bunx --no-install wrangler types
          --env-interface CloudflareBindings
          --check

  build:deps:
    label: '{{.TASK}}@{{.BUILD_PROFILE}}'
    requires:
      vars:
        - name: BUILD_PROFILE
          enum: [development, release]
    deps:
      - task: typegen
      - task: :hono:build
        vars:
          BUILD_PROFILE: '{{.BUILD_PROFILE}}'
      - task: :shared:build
        vars:
          BUILD_PROFILE: '{{.BUILD_PROFILE}}'

  build:bundle:
    label: '{{.TASK}}@{{.TARGET_ENVIRONMENT}}'
    requires:
      vars:
        - name: TARGET_ENVIRONMENT
          enum: [local, ci]
    sources:
      - './package.json'
      - './worker-configuration.d.ts'
      - './wrangler.jsonc'
      - './src/**/*.ts'
      - './tsconfig/**/*.json'
      - '{{.ROOT_DIR}}/packages/shared/dist/release/**/*'
      - '{{.SOURCES.tsconfigPackage}}'
      - '{{.SOURCES.tsconfigs}}'
      - '{{.SOURCES.lockfile}}'
    generates:
      - './dist/**/*'
    deps:
      - task: build:deps
        vars:
          BUILD_PROFILE: release
    cmds:
      - >
        bunx --no-install wrangler deploy
        --dry-run
        --env {{.TARGET_ENVIRONMENT}}
        --outdir ./dist
        --metafile ./dist/bundle-meta.json

  build:bundle:dev:
    cmds:
      - task: build:bundle
        vars:
          TARGET_ENVIRONMENT: local

  build:docker:
    label: '{{.TASK}}@{{.IMAGE_TAG}}:{{.TARGET_ENVIRONMENT}}:{{.DOCKER_TARGET}}'
    requires:
      vars:
        - name: TARGET_ENVIRONMENT
          enum: [local, ci]
        - name: DOCKER_TARGET
          enum: [runtime, base, build-deps, code, bundle, runtime-deps]
    vars:
      IMAGE_TAG: '{{.DIN_APP_WORKER}}:local'
    cmds:
      - >
        docker buildx build
        --load
        --file ./Dockerfile.app-worker
        --build-arg TARGET_ENVIRONMENT={{.TARGET_ENVIRONMENT}}
        {{if ne .DOCKER_TARGET "runtime"}}
        --target {{.DOCKER_TARGET}}
        {{end}}
        --tag {{.IMAGE_TAG}}
        {{.ROOT_DIR}}

  build:docker:dev:
    cmds:
      - task: build:bundle
        vars:
          TARGET_ENVIRONMENT: local
          DOCKER_TARGET: runtime

  start:dev:
    vars:
      ENV:
        sh: yq '.env.local.vars' ./wrangler.jsonc
    deps:
      - task: build:deps
        vars:
          BUILD_PROFILE: development
    cmds:
      - >
        bunx --no-install wrangler dev
        --env local
        --port {{(.ENV | fromJson).PORT}}

  start:bundle:
    vars:
      ENV:
        sh: yq '.env.local.vars' ./wrangler.jsonc
    cmds:
      - task: build:bundle
        vars:
          TARGET_ENVIRONMENT: local
      - >
        bunx --no-install wrangler dev
        --env local
        --no-bundle
        --port {{(.ENV | fromJson).PORT}}
        ./dist/index.js

  start:bundle:dev:
    cmds:
      - task: start:bundle
        vars:
          TARGET_ENVIRONMENT: local

  start:docker:
    interactive: true
    requires:
      vars:
        - name: TARGET_ENVIRONMENT
          enum: [local, ci]
        - name: DEV_MODE
          enum: ['true', 'false']
    vars:
      ENV:
        sh: yq '.env["{{.TARGET_ENVIRONMENT}}"].vars' ./wrangler.jsonc
    cmds:
      - task: build:docker
        vars:
          TARGET_ENVIRONMENT: '{{.TARGET_ENVIRONMENT}}'
      - >
        docker run
        {{if ne .DEV_MODE "true"}}
        --detach
        {{end}}
        {{if eq .DEV_MODE "true"}}
        --interactive
        --tty
        --entrypoint bash
        {{end}}
        --rm
        --init
        --ipc=host
        --publish {{(.ENV | fromJson).PORT}}:{{(.ENV | fromJson).PORT}}
        --ulimit nofile=65536:65536
        --ulimit core=0:0
        --ulimit memlock=-1:-1
        --name={{.DIN_APP_WORKER}}
        {{.DIN_APP_WORKER}}:local
        {{if ne .DEV_MODE "true"}}
        dev
        --env {{.TARGET_ENVIRONMENT}}
        --no-bundle
        --ip 0.0.0.0
        --port {{(.ENV | fromJson).PORT}}
        ./index.js
        {{end}}

  deploy:
    requires:
      vars:
        - name: TARGET_ENVIRONMENT
          enum: [testing, production]
    cmds:
      - bunx --no-install wrangler deploy --env {{.TARGET_ENVIRONMENT}} --minify
      - bunx --no-install wrangler deployments list --env {{.TARGET_ENVIRONMENT}}
